### ISSUE TITLE
Dataset in CoronaWhy Dataverse

### ISSUE THREAD

**Issue by geek80** [kalyaniuniversity/COVID-19-Datasets#1]
Hello,Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/GNIDE1

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by onclave** [comment]
@geek80 yes of course. Do let us know what we can do from our end. Also, if you'd like to contribute information to our datasets, do let us know what other information we can add to the existing repository and we would look into how we can do that!

**Comment by geek80** [comment]
Great, thank you. Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and I'll give you the Dataset creator permissions to your dataset. Then please add relevant metadata - description and keywords to your dataset.

**Comment by onclave** [comment]
@geek80 Hello, we have registered with CoronaWhy with the username `debabrata_acharya` but we have not yet received the verification email. What should be my next step?

**Comment by geek80** [comment]
Hi, You have been given the author permissions for your dataset. Please add relevant metadata description and keywords and keep the dataset up to date. Thanks.
